import React from "react";
import { motion } from "framer-motion";
import {
  ShieldCheck,
  FileText,
  AlertTriangle,
  LockKeyhole,
  Database,
  UserCheck,
  Leaf,
  Scale,
} from "lucide-react";

export default function TermsAndPrivacy() {
  return (
    <main className="min-h-screen bg-paper-1 px-4 pt-24 pb-12 sm:px-6 md:px-8 lg:px-12 lg:pt-28">
      <div className="mx-auto max-w-5xl">

        {/* ============================================================
            HEADER
        ============================================================ */}

        <motion.section
          initial={{ opacity: 0, y: 25 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: "easeOut" }}
          className="mb-10"
        >
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-muted/20 bg-muted/5 px-4 py-2">
            <ShieldCheck className="size-4 text-muted" />

            <span className="font-secondary text-xs font-medium text-secondary">
              TERMS & PRIVACY
            </span>
          </div>

          <h1 className="font-primary text-3xl font-semibold tracking-tight text-primary sm:text-4xl lg:text-5xl">
            Terms of Service & Privacy Policy
          </h1>

          <p className="mt-4 max-w-3xl font-secondary text-sm leading-relaxed text-secondary sm:text-base">
            Please read these terms carefully before using our leaf
            classification platform. By using this website, you agree to the terms
            described below.
          </p>

          <p className="mt-3 font-secondary text-xs text-secondary/70">
            Last updated: August 23, 2026
          </p>
        </motion.section>

        {/* ============================================================
            IMPORTANT DISCLAIMER
        ============================================================ */}

        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="mb-8 rounded-2xl border border-amber-500/20 bg-amber-500/5 p-5 sm:p-6"
        >
          <div className="flex items-start gap-4">
            <div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-amber-500/10">
              <AlertTriangle className="size-5 text-amber-500" />
            </div>

            <div>
              <h2 className="font-primary text-base font-semibold text-primary sm:text-lg">
                Important Disclaimer
              </h2>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                This website uses artificial intelligence and machine learning
                models to analyze uploaded leaf images and generate
                predictions. These predictions are provided for
                <strong> educational, research, and informational purposes only.</strong>
              </p>

              <p className="mt-3 font-secondary text-sm leading-relaxed text-secondary">
                The predictions may be inaccurate, incomplete, or incorrect.
                AI models can make mistakes due to image quality, differences
                between datasets, unusual cases, model limitations, or other
                factors. A prediction from this website should{" "}
                <strong>never be considered a definitive plant disease
                diagnosis, agronomic advice, or a substitute for a qualified
                plant pathologist or agricultural extension officer.</strong>
              </p>

              <p className="mt-3 font-secondary text-sm leading-relaxed text-secondary">
                Do not make treatment, pesticide, or crop-management
                decisions solely on the basis of results generated by this
                website. Always consult a qualified agronomist or other appropriate
                plant health professional for interpretation and
                decisions.
              </p>
            </div>
          </div>
        </motion.section>

        {/* ============================================================
            TERMS OF SERVICE
        ============================================================ */}

        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.05 }}
          className="rounded-2xl border border-muted/20 bg-paper-1 p-5 shadow-[0_8px_30px_color-mix(in_srgb,var(--color-muted)_6%,transparent)] sm:p-7 lg:p-9"
        >
          <div className="flex items-center gap-3 border-b border-muted/10 pb-5">
            <div className="flex size-10 items-center justify-center rounded-xl bg-muted/10">
              <FileText className="size-5 text-muted" />
            </div>

            <div>
              <h2 className="font-primary text-xl font-semibold text-primary sm:text-2xl">
                Terms of Service
              </h2>

              <p className="mt-1 font-secondary text-xs text-secondary">
                Rules and conditions for using this website
              </p>
            </div>
          </div>

          <div className="mt-7 space-y-8">

            {/* 1 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                1. Acceptance of Terms
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                By accessing or using this website, you acknowledge that you
                have read, understood, and agreed to these Terms of Service and
                our Privacy Policy. If you do not agree with these terms,
                please do not use the website.
              </p>
            </section>

            {/* 2 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                2. Purpose of the Platform
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                This platform provides an AI-based leaf image analysis
                system designed for educational, research, demonstration, and
                informational purposes. The system may analyze leaf images
                relating to conditions such as leaf spot, blight, rust,
                mildew, or other supported disease categories.
              </p>

              <p className="mt-3 font-secondary text-sm leading-relaxed text-secondary">
                The platform is not intended to replace professional plant
                inspection, diagnosis, treatment, or crop-management decision-making.
              </p>
            </section>

            {/* 3 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                3. AI Predictions and Model Limitations
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                Our system uses trained machine learning and artificial
                intelligence models to generate predictions from uploaded
                images. Although efforts may be made to train and evaluate
                these models, no AI model can guarantee completely accurate
                results.
              </p>

              <p className="mt-3 font-secondary text-sm leading-relaxed text-secondary">
                Predictions may be affected by image quality, lighting,
                resolution, cropping, positioning, artifacts, uncommon
                conditions, differences between training and real-world
                images, and other factors.
              </p>

              <p className="mt-3 font-secondary text-sm leading-relaxed text-secondary">
                A high confidence score does not necessarily mean that a
                prediction is correct. Similarly, a low confidence
                score does not necessarily mean that a leaf disease is
                absent.
              </p>
            </section>

            {/* 4 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                4. No Professional Diagnosis
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                Nothing provided by this website should be interpreted as a
                diagnosis, agronomic opinion, treatment recommendation,
                prescription, or professional plant-health advice.
              </p>

              <p className="mt-3 font-secondary text-sm leading-relaxed text-secondary">
                Users should consult a qualified agronomist or plant
                pathologist for diagnosis and treatment. If you believe a
                crop has a serious or urgent disease issue, seek appropriate
                professional assistance rather than relying on this platform.
              </p>
            </section>

            {/* 5 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                5. User Responsibilities
              </h3>

              <ul className="mt-3 list-disc space-y-2 pl-5 font-secondary text-sm leading-relaxed text-secondary">
                <li>
                  You are responsible for the information and images you upload.
                </li>
                <li>
                  You should only upload images that you are legally permitted
                  to use.
                </li>
                <li>
                  You should not use the platform as the sole basis for making
                  crop-treatment decisions.
                </li>
                <li>
                  You should keep your account credentials secure.
                </li>
                <li>
                  You should not attempt to misuse, attack, reverse engineer,
                  or disrupt the platform.
                </li>
              </ul>
            </section>

            {/* 6 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                6. Account Security
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                Some features require an account. You are responsible for
                maintaining the confidentiality of your login credentials and
                for activities performed through your account.
              </p>

              <p className="mt-3 font-secondary text-sm leading-relaxed text-secondary">
                If you believe your account has been accessed without your
                permission, you should change your password and contact the
                platform administrators.
              </p>
            </section>

            {/* 7 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                7. Availability and Changes
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                We may modify, update, suspend, or discontinue parts of the
                website or its features at any time. We do not guarantee that
                the website will always be available, uninterrupted, or
                error-free.
              </p>
            </section>

            {/* 8 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                8. Limitation of Liability
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                To the extent permitted by applicable law, the developers and
                operators of this platform are not responsible for decisions,
                actions, losses, damages, or consequences resulting from
                reliance on AI-generated predictions or information provided
                through the website.
              </p>
            </section>

            {/* 9 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                9. Intellectual Property
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                Unless otherwise stated, the website's software, interface,
                branding, graphics, content, and other materials are protected
                by applicable intellectual property laws. You may not copy,
                reproduce, distribute, or commercially exploit these materials
                without appropriate permission.
              </p>
            </section>

            {/* 10 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                10. Changes to These Terms
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                We may update these Terms of Service from time to time. Updated
                terms will be posted on this page. Continued use of the website
                after changes are posted indicates acceptance of the updated
                terms.
              </p>
            </section>
          </div>
        </motion.section>

        {/* ============================================================
            PRIVACY POLICY
        ============================================================ */}

        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="mt-8 rounded-2xl border border-muted/20 bg-paper-1 p-5 shadow-[0_8px_30px_color-mix(in_srgb,var(--color-muted)_6%,transparent)] sm:p-7 lg:p-9"
        >
          <div className="flex items-center gap-3 border-b border-muted/10 pb-5">
            <div className="flex size-10 items-center justify-center rounded-xl bg-muted/10">
              <LockKeyhole className="size-5 text-muted" />
            </div>

            <div>
              <h2 className="font-primary text-xl font-semibold text-primary sm:text-2xl">
                Privacy Policy
              </h2>

              <p className="mt-1 font-secondary text-xs text-secondary">
                How information may be collected and used
              </p>
            </div>
          </div>

          <div className="mt-7 space-y-8">

            {/* 1 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                1. Information We Collect
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                Depending on how you use the website, we may collect information
                such as your name, email address, account information, profile
                photo, uploaded leaf images, prediction history, and
                information you provide through the contact form.
              </p>
            </section>

            {/* 2 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                2. Account Information
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                When you create an account, information such as your name and
                email address may be stored to provide authentication,
                account-management, and related services.
              </p>

              <p className="mt-3 font-secondary text-sm leading-relaxed text-secondary">
                Passwords are not intended to be stored in plain text and are
                protected using password hashing mechanisms.
              </p>
            </section>

            {/* 3 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                3. Leaf Images
              </h3>

              <div className="mt-3 rounded-xl border border-muted/10 bg-muted/5 p-4">
                <div className="flex items-start gap-3">
                  <Database className="mt-0.5 size-5 shrink-0 text-muted" />

                  <p className="font-secondary text-sm leading-relaxed text-secondary">
                    Leaf images uploaded to the platform may be processed
                    by our backend and AI models to generate predictions and
                    may be stored as part of your prediction history, depending
                    on the features being used.
                  </p>
                </div>
              </div>

              <p className="mt-3 font-secondary text-sm leading-relaxed text-secondary">
                Users should avoid uploading unnecessary personally
                identifiable information contained within leaf images.
                Where possible, remove information that is not required for
                analysis.
              </p>
            </section>

            {/* 4 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                4. How Information Is Used
              </h3>

              <ul className="mt-3 list-disc space-y-2 pl-5 font-secondary text-sm leading-relaxed text-secondary">
                <li>To provide and operate the website.</li>
                <li>To authenticate users and manage accounts.</li>
                <li>To process uploaded images and generate predictions.</li>
                <li>To maintain prediction history.</li>
                <li>To respond to contact or support queries.</li>
                <li>To maintain security and prevent misuse.</li>
                <li>To improve the reliability and functionality of the platform.</li>
              </ul>
            </section>

            {/* 5 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                5. Contact Form Information
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                Information submitted through the Contact Us form, including
                your name, email, subject, and message, may be stored so that
                the platform administrators can review and respond to your
                query.
              </p>
            </section>

            {/* 6 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                6. Third-Party Services
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                The platform may use third-party services for infrastructure,
                image storage, authentication-related functionality, email
                delivery, database services, hosting, or other technical
                requirements.
              </p>

              <p className="mt-3 font-secondary text-sm leading-relaxed text-secondary">
                Information processed by such services may be subject to their
                respective terms and privacy policies.
              </p>
            </section>

            {/* 7 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                7. Data Security
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                We take reasonable technical and organizational measures to
                protect information handled by the platform. However, no
                internet-based service can guarantee absolute security.
              </p>
            </section>

            {/* 8 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                8. Data Retention
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                Information may be retained for as long as necessary to
                provide the relevant services, maintain account and prediction
                history, comply with applicable requirements, resolve disputes,
                or maintain security.
              </p>
            </section>

            {/* 9 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                9. Your Responsibility
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                You should not upload information belonging to another person
                unless you have appropriate permission or a lawful basis to do
                so. You are responsible for ensuring that your use of the
                platform complies with applicable laws and regulations.
              </p>
            </section>

            {/* 10 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                10. Children's Privacy
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                The platform is not specifically designed to collect personal
                information from children. Users should not provide personal
                information belonging to children unless permitted by a parent,
                guardian, or applicable law.
              </p>
            </section>

            {/* 11 */}
            <section>
              <h3 className="font-primary text-base font-semibold text-primary">
                11. Privacy Policy Updates
              </h3>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                This Privacy Policy may be updated when our services,
                technology, or practices change. Any updated version will be
                published on this page.
              </p>
            </section>
          </div>
        </motion.section>

        {/* ============================================================
            FINAL ACKNOWLEDGEMENT
        ============================================================ */}

        <motion.section
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.15 }}
          className="mt-8 rounded-2xl border border-muted/20 bg-muted/5 p-5 sm:p-6"
        >
          <div className="flex items-start gap-4">
            <div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-muted/10">
              <UserCheck className="size-5 text-muted" />
            </div>

            <div>
              <h2 className="font-primary text-base font-semibold text-primary">
                By using this website
              </h2>

              <p className="mt-2 font-secondary text-sm leading-relaxed text-secondary">
                You acknowledge that you understand the limitations of
                artificial intelligence and agree that the predictions
                generated by this platform are not guaranteed to be accurate.
                You also acknowledge that these predictions should not be used
                as a replacement for professional agronomic advice, diagnosis,
                or treatment.
              </p>
            </div>
          </div>
        </motion.section>

        {/* ============================================================
            BOTTOM DISCLAIMER
        ============================================================ */}

        <div className="mt-8 flex flex-col items-center justify-center gap-2 text-center">
          <div className="flex items-center gap-2">
            <Leaf className="size-4 text-secondary/60" />

            <span className="font-secondary text-xs font-medium text-secondary/70">
              AI-assisted leaf image analysis
            </span>
          </div>

          <p className="max-w-2xl font-secondary text-xs leading-relaxed text-secondary/60">
            This platform is intended for educational and informational use.
            Always consult a qualified agronomist or plant pathologist for
            diagnosis and treatment decisions.
          </p>
        </div>
      </div>
    </main>
  );
}